"""added User.ist_vorstand

Revision ID: 17d7af02d17f
Revises: 4eda6570533e
Create Date: 2022-06-11 12:16:35.900757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d7af02d17f'
down_revision = '4eda6570533e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ist_vorstand', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ist_vorstand')
    # ### end Alembic commands ###
