"""added User.sichtbar

Revision ID: 4eda6570533e
Revises: 942b84cfdc9f
Create Date: 2022-05-28 21:44:16.083066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eda6570533e'
down_revision = '942b84cfdc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sichtbar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sichtbar')
    # ### end Alembic commands ###
